<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>秒杀商品查询</title>
</head>
<body>
<form>
    商品id:${msproductinfo.productid}</br>
    商品标题:${msproductinfo.producttitle}</br>
    商品图片地址:${msproductinfo.productpic}</br>
    商品原价格:${msproductinfo.originalprice}</br>
    秒杀价格:${msproductinfo.miaoshaprice}</br>
    商家id:${msproductinfo.merchantid}</br>
    商品申请时间:${msproductinfo.applydate}</br>
    商品审核时间:${msproductinfo.auditdate}</br>
    商品审核状态:${msproductinfo.auditstate}</br>
    秒杀开始时间:${msproductinfo.starttimeStr}</br>
    秒杀结束时间:${msproductinfo.endtimeStr}</br>
    秒杀商品数量:${msproductinfo.productcount}</br>
    剩余库存数:${msproductinfo.stockcount}</br>
    商品描述:${msproductinfo.description}</br>
</form>
</body>
</html>
